# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TableViewDemo
  pod 'SnapKit' # https://github.com/SnapKit/SnapKit

  target 'TableViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TableViewDemoUITests' do
    # Pods for testing
  end

end
